# Generated by Django 3.1.5 on 2021-01-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(default=36.6)),
                ('breathing_rate', models.IntegerField(default=18)),
                ('hct', models.IntegerField(default=0.42)),
                ('diuresis', models.IntegerField(default=1000)),
                ('Na', models.IntegerField(default=140)),
                ('K', models.IntegerField(default=4.5)),
                ('Glu', models.IntegerField(default=5)),
                ('Urea', models.IntegerField(default=5)),
                ('pH', models.IntegerField(default=7.4)),
                ('Cl', models.IntegerField(default=102)),
                ('BE', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='General_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=40)),
                ('mass', models.IntegerField(default=70)),
                ('day_of_disease', models.IntegerField(default=0)),
                ('diagnosis', models.CharField(max_length=100)),
            ],
        ),
    ]
