# Generated by Django 3.1.5 on 2021-01-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_electrolits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analizes',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
    ]
