# Generated by Django 3.1.5 on 2021-01-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_electrolits', '0003_auto_20210104_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='analizes',
            name='patient_indicators',
            field=models.ManyToManyField(to='water_electrolits.General_Information'),
        ),
        migrations.AddField(
            model_name='general_information',
            name='male',
            field=models.CharField(default='male', max_length=100),
        ),
    ]
