# Generated by Django 3.1.5 on 2021-01-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_electrolits', '0004_auto_20210104_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general_information',
            old_name='male',
            new_name='sex',
        ),
    ]
