# Generated by Django 3.1.5 on 2021-02-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_electrolits', '0005_auto_20210104_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pe_id', models.CharField(max_length=100)),
            ],
        ),
    ]
